### PR TITLE
Backport fixes to 3.x build: #1131 and #1121, bug: #1099 and test:#1047

### PR DESCRIPTION
**Pull request by igorT**
https://github.com/hjdivad/ember-m3/pull/1099
https://github.com/hjdivad/ember-m3/pull/1131
https://github.com/hjdivad/ember-m3/pull/1121
https://github.com/hjdivad/ember-m3/pull/1047

### CODE REVIEW

**Comment by hjdivad** [comment]
https://github.com/hjdivad/ember-m3/pull/1131

**Comment by igorT** [comment]
Added backport PR numbers to PR title

**Comment by igorT** [comment]
The CI fails on release/3-0-x branch as is, seems to be a dependency issue

**Comment by igorT** [comment]
@hjdivad CI is green

**Pull request merged**
